### ISSUE TITLE
Casos de Uso - Diagrama General

### ISSUE THREAD

**Issue by EvelynMC** [EvelynMC/Modulo-Compras#5]
Elaboración de Diagrama general de Casos de Uso. No es requerido por el profesor diagramas por casos de uso individuales. Sin embargo, se evaluará hacerlo para mejora del trabajo de análisis final.

**Comment by EvelynMC** [comment]
Señorcitos,
Haré el diagrama de CU en starUML por mientras, pero siempre sometido a revisión por ustedes. Sientanse libres de dejar comentarios de las modificaciones y las razones de sus modificaciones.

**Comment by EvelynMC** [comment]
Está arriba una primera versión de los casos de uso general. Subo una imagen preliminar aquí por cualquier cosa: 

![cu - general](https://user-images.githubusercontent.com/24615400/28999665-ac689fca-7a1d-11e7-95f8-bb97177979d8.jpg)

**Comment by jcbustamantep** [comment]
No me gusto, no hay relacion entre los actores, al menos una clase deberiabser compartiva

**Comment by EvelynMC** [comment]
Dale, modifica si gustas los cambios en el archivo de star uml y subes una nueva imagen con tus propuestas 😉

**Comment by EvelynMC** [comment]
Modificados diagrama general de caso de uso y anexados los individuales por requerimientos. Validar el miércoles 8 en clases.

**Comment by EvelynMC** [comment]
Se valida con profesor diagrama único general, donde deben estar representados todos los requerimientos funcionales.

Se cierra ISSUE.
